import torch
import esm
import sys
import math
import warnings
from pathlib import Path
from rdkit import Chem
from rdkit.Chem import MACCSkeys
from torch_geometric.data import Data, Batch

# --------------------------
# 1. 配置与初始化（替换为你的实际路径）
# --------------------------
warnings.filterwarnings("ignore", message="Regression weights not found")
CODE_DIR = Path("D:/vscode/Xvess/EITLEM-Kinetics/Code")
sys.path.append(str(CODE_DIR.absolute()))
WEIGHTS_ROOT = Path("D:/vscode/Xvess/EITLEM-Kinetics/Weights")
MODEL_PATHS = {
    'KCAT': str(WEIGHTS_ROOT / "KCAT/iter8_trainR2_0.9408_devR2_0.7459_RMSE_0.7751_MAE_0.4787"),
    'KM': str(WEIGHTS_ROOT / "KM/iter8_trainR2_0.9303_devR2_0.7163_RMSE_0.6960_MAE_0.4802"),
    'KKM': str(WEIGHTS_ROOT / "KKM/iter8-trainR2_0.9091_devR2_0.8325_RMSE_0.7417_MAE_0.4896")
}

# --------------------------
# 2. 导入模块与初始化模型
# --------------------------
try:
    from KCM import EitlemKcatPredictor
    from KMP import EitlemKmPredictor
    from ensemble import ensemble as EitlemKKMPredictor
except ImportError as e:
    raise ImportError(f"导入失败：{e}")

def init_models():
    device = torch.device("cpu")
    esm_model, alphabet = esm.pretrained.esm1v_t33_650M_UR90S_1()
    esm_model = esm_model.to(device).eval()
    batch_converter = alphabet.get_batch_converter()

    def load_model(kinetics_type):
        if kinetics_type == 'KCAT':
            model = EitlemKcatPredictor(167, 512, 1280, 10, 0.5, 10)
        elif kinetics_type == 'KM':
            model = EitlemKmPredictor(167, 512, 1280, 10, 0.5, 10)
        elif kinetics_type == 'KKM':
            model = EitlemKKMPredictor(167, 512, 1280, 10, 0.5, 10)
        model.load_state_dict(torch.load(MODEL_PATHS[kinetics_type], map_location=device))
        return model.to(device).eval()

    return {
        'device': device,
        'esm_model': esm_model,
        'batch_converter': batch_converter,
        'alphabet': alphabet,
        'kcat_model': load_model('KCAT'),
        'km_model': load_model('KM'),
        'kkm_model': load_model('KKM')
    }

# --------------------------
# 3. 批量预测函数
# --------------------------
def batch_predict(models, enzyme_list, substrate_smiles):
    device = models['device']
    esm_model = models['esm_model']
    batch_converter = models['batch_converter']
    results = []

    for enzyme_name, sequence in enzyme_list:
        # 提取蛋白质特征
        protein_data = [(enzyme_name, sequence)]
        _, _, batch_tokens = batch_converter(protein_data)
        batch_tokens = batch_tokens.to(device)
        batch_lens = (batch_tokens != models['alphabet'].padding_idx).sum(1)
        with torch.no_grad():
            esm_results = esm_model(batch_tokens, repr_layers=[33], return_contacts=False)
        protein_embed = esm_results["representations"][33][0, 1:batch_lens[0]-1]

        # 提取底物特征
        mol = Chem.MolFromSmiles(substrate_smiles)
        maccs = MACCSkeys.GenMACCSKeys(mol).ToList()
        substrate_feat = torch.FloatTensor(maccs).unsqueeze(0).to(device)

        # 构造数据并预测
        data = Data(x=substrate_feat, pro_emb=protein_embed)
        input_batch = Batch.from_data_list([data], follow_batch=['pro_emb'])
        
        with torch.no_grad():
            kcat = math.pow(10, models['kcat_model'](input_batch)[0].item())
            km = math.pow(10, models['km_model'](input_batch)[0].item())
            kkm = math.pow(10, models['kkm_model'](input_batch)[0].item())
        
        results.append({
            '酶名称': enzyme_name,
            'kcat值': round(kcat, 4),
            'KM值': round(km, 4),
            'kcat/KM值': round(kkm, 4)
        })
    return results

# --------------------------
# 4. 输入你的酶数据并运行
# --------------------------
if __name__ == "__main__":
    # 整理所有酶的序列
    enzyme_list = [
        ("CYP706X1", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPKGLPLVGSLPFLGPNIHQELTKISHQYGPIFKLYLGSKLHIVVNSAELAKVITAEQDESFANRAPHIAGLATSYGGNDIAFAPNNANRRNLRKVLVQEVLSNVNLEASHAYRRHEVRKAVKYVYDRVGMDVDINEISFSTVLNVFTNIIWRKGFVDDGANYANLSENIQKVICRIVEIAEGLNISDFFPMLARFDLQGVERKMKDQMKQFDKIIEPTIKERMNSRSTNVEETVEHKGRKDFLQILLEHTDQKNGTSITMTQLKALVADIFLGGTDATSAMVEWAMTEIFRDQKVMKRVQDELEEIVGLNNIVEESHIPKLKYLEAVCKETFRLHPPIPFLLPRAPIKSCTVGGYTVPEGATIFVNVWAIQRDPRHWENPSEFNPDRFLNRNGSTEKWDYSGTNLTFLPFGSGRRRCPGIPLGEKMMMHILASLMHSFDWKLPNGEELDLSERFGIALKKKKPLVAVPTKRLSDLSLYM"),
        ("Design11361", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPKGLPLVGFLPFLGPNLHLDLLKMANNYGPIFKLYLGSNLHIVVNSADLAKVVTGEQDESFANRAQHIAGLATSYNASDIAFADNNANRRKLRKVLVHEVLSNVNLEASNAYRRREVRKTIKNVHEIIGNEVDINEIAFSTVLSVLTSIVFGKSMVKGAKYSNLVADMRKFVSGVVEIAGGLNISDFFPVLARFDFQGVKRKMADQMKMFDKIFETSVEERINSRSAIIEETVKQEGRKDFLQILLELLDQNTETSITMTQLKALVVDIFLGGTDATSAMVEWAMTEIFRDKKVMKRVQDELAEVVGLNNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTVPKGSTIFLNVWAIQRDPQYWENPSDFNPERFLNYKGSNKWDYAGTNLKFFPFGSGRRRCPGVSLGEKMLMHILASLLHSFDWSLPTGQKLDLSDKFGITLKKRKPLIAVPSPRLSDASLYL"),
        ("Design33380", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPSPKSLPIVGHLPFLGTDIHHELTEISHQYGPIFKFHLGSKLHIIINSAELAKVITVEQDESFANRWPHIAGIATSYGGNDIAFAPNNANWRNLRKVLVQEVLSNVNLEASHAYRRHEVRKAVKYVYDRVGMDVDINEISFSTVLNVFSNIIWRKGFVDDGTNYANLSEKIQKVICRIVEIAEGLNISDFFPMLARFDLQGVERKMKTQMKQFDKIFETTVDERINSKPAISEEAVKEEGRKDFLQILLELLDQNTATSITMTQMKALVVDVFLGGTDATSAMTEWAMTEILRNRQVMKKVQDELAEVVGLNNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTVPKGSTIFLNVWAIQRDPQHWTNPSEFNPERFLNKGSEKWDYNGTNSKYFPFGSGRRRCPGIPLGEKMMMHILASLMHSFDWSLPRGEEHDLSDKFGIAMKKKMPLVLIPSQRLSDHNLYM"),
        ("Design58683", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPKGLPVVGFLPFLGPNLHLDFLTLVHKYGPIFKLYLGSNLHIVVNSADLAKVVTGEQDESFANRAQHIAGLATSYNASDIAFADNNANRRKLRKVLVHEVLSNVNLEASNAFRRREVRKTIKNVHEIIGNEVDINEIAFSTVLSVLTSIVFGKSMVKGAKYSNLVAEMRKFVSGVVEIAGELNISDFFPMLARFDFQGVKRRMAQQMKIFDRIFETTIEERTGSTSGIIDQKVKEEGRKDFLQILLELLDQNTGTSITMTQLKALVVDIFLGGTDATSAMVEWAMTEIFRDKKVMKRVQDELAEVVGLHNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTVPKGSTIFLNVWAIQRDPRYWENPSDFNPERFLNYKGSEKWDYSGTNLKFFPFGSGRRRCPGVPLGEKMMMHILASLLHSFDWSLPTGEKLDLSDKFGITLKKRKPLIAIPSMRLSDASLYM"),
        ("Design6444", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPKGLPLVGFLPFLGPNLHLDFLTMAHQYGPIFKLYLGSNLHIVVNSADLAKVVTGEQDESFANRAQHIAGLATSYNASDILFADNNANRRKLRKVLVHEVLSNVNLEASNAYRRREVRKTIKNVHEIIGNEVDINEIAFSTVLSVLTSIVFGKSMVKGAKYSNLVADMRKFVSGVVEIAGGLNISDFFPMLARFDFQGVKRKMAQQMKMFDKIFESTVEERVGSTSGIIEEAVKQEGRKDFLQILLELLDQNTETSITMTQMKALVVDIFLGGTDATSAMVEWAMTEIFRDKKVMKRVQDELAEVVGLHNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTVPKGSTIFLNVWAIQRDPQYWENPSEFNPERFLNYKGSEKWDYTGTNLKFFPFGSGRRRCPGVPLGEKMMMHILASLLHSFDWSLPNGQKLDLSDKFGITLKKRKPLIAVPSLRLSDASLYV"),
        ("Design84497", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPRGLPLVGYLPFLGPQPHRSLSEISHRYGPIFKLQLGTKLWIVVNSAELAKVIHVEQDESFANRAPHIAGLATSYGGNDIAFAPNNANRRNLRKLLVQEVLSNVNLEASHAYRRHEVRKAVKYVYDRVGMDIDINEISFTTVINVFFNIWRMGFIDDQSNIGNLLEKIQKVICRIVEIAEGLNISDFFPVLARFDLQRVERKMKDQMKQFDKIIETTIKERMNSKSTNVEETVEQEGRKDFLQILLELLDQSTATSITMTQLKALVVDVFLGGTDATSAMVEWAMTEILRNRQVMKKVQDELAQVVGLHNVVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTVPKGSTIFLNVWAIQRDPQHWTNPSEFNPERFLNYKGSEKWDYAGTNSKFFPLGSGRRRCPGIPLGEKMMMHILASLLHSFDWSLPTGQKLDLSDKFGIAMKKKKPLVVVPSLRLSDLSLYS"),
        ("Design91808", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPKGLPIVGYLLFLGTNLHIHFSNLSQSYGPIFKFHLGNKLWVIVNTAELAKTIVVEQDESFANRWPHIAGLATSYGGNDIAFAPNNANRRNLRKVLVQEVLSNVNLEASHNYRRHEVRKAVKYVYDRVGMDIDINEISFTTVLNVFFNIIWRMGFEDDQTNVGNLLQKIQKVICRIVEIAEGLNISDFFPVLARFDVQRVERKMKDQMKQFDKIIETTIKERMNSKSTNVEETVEQKGRKDFLQILLELLDQNNETSITMTQMKALVVDIFLGGTDATSAMVEWAMTEILRNRQVMKKVQDELAEIVGLNNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKTCTVGGYTVPKGSTIFLNVWAIQRDPQYWDNPSEFNPERFLNYKGSEKWDYNGTNLKFFPFGSGRRRCPGIPLGEKMMMHILASLMHSFDWSLPRGEELDLSDKFGIAMKKKKPLVVIPSLRLSDHNLYM"),
        ("Design49566", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPPLPPGPKGLPLVGSLPFLGPNIHQELTKITHQYGPIFKLYLGSKLHIVVNSAELAKVITAEQDESFANRAPHIAGLATSYGGNDIAFAPNNANRRNLRKVLVQEVLSNVNLEASHAYRRHEVRKAVKYVHERVGMEVDINKIAFSTVLSVLTNIVWAKSVVDDGANYSNEVQNIISRVVEIAGGLNISFFVMAQIDFQGVERRMKKQMKQFDKIIEMTIEERMNSSKNEAKTKEEGRKDFLQILLEQQQQNTETSITMTQMKALVVDIFLGGTDATSAMVEWAMTEILRDQQVMKRVQDELEEIVGLNNVEESHLPKLKYLDAVFKETFRLHPPIPFLLPRAPIKSCTVGGYTVPEGATIFVNVWAIQRDPQRWENPSEFNPDRFLNRNGSTGKWDYSGTNLTFLPFGSGRRRCPGIPLGEKMMMHILASLLHSFDWKLPNGQKLELSERFGIALKKKKPLVAVPTKRLDVSLYM"),
        ("Design12854", "MAALNTHGSWWPAEGNGGKNDGDLPLALLAVITAALLPLLWYKRSISSSQNGAPPLPPGPKGLPVVGYLPFLGPNLHLDYLTMVHQYGPIFKIYLGSNLHIVVNSVDLAKVVTGEQDESFANRAQHIAGLATSYNASDIAFADNNANRRKLRKVLVHEVLSNVNLEASNAYRRREVRKTIKNVHEVIGNEVDINEISFSTVLSVLTSIVFGKSMVKGAKYSNLAADIRKFVSGVVEIAGGLNISDFFPMLARFDFQGVEQRMKTQMKMFDKIFETSVEERINSRSAIKEEAVKEEGRKDFLQILLELLEQNTETSITMTQMKALVVDVFLGGTDATSAMVEWAMTEIFRNRQVMKKVQDELAEIVGLHNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKTCTVGGYTVPKGSTIFLNVWAIQRDPKYWDNPSDFNPERFLNYEGEKWDYNGTNLKFFPFGSGRRRCPGIPLGEKMMMHILASLLHSFNWSLPEGEDHDLSEKFGIAMKKKKPLIAIPSLRLSDHNLYM"),
        ("Design33105", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPRGLPLVGYLPFLGPNLHQELTKMAHRYGPIFKLYLGSKLHIVVNSADLAKVVTGEQDESFANRAPHIAGLATSYNASDIAFADNNANRRKLRKVLVHEVLSNVNLEASHAYRRREVRKTIKNVHEIIGNEVDINEIAFSTVLSVLTSIVWGKSMVKGASNMIVEVRKFVSGVVEIAGELNISDFFPMLARFDFQGVERRMKKQMKLFDKIFESTVEERINSRSIIKEEAASKEENRRKDFLQILLELQEQNNTSITMTQMKALVVDIFLGGTDATSAMIEWAMTEILRNRRVMKKVQDELAEIVGLQNNVEEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTIPKGSTIFLNVWAIQRDPQYWENPSEFNPERFLNYKGSEKWDYAGTNSKFFPLGSGRRRCPGVSLGEKMMMHILASLLHSFDWSLPTGQKLDLSDKFGIALKKRKPLIAVPSPRLNDASLYM"),
        ("Design42565", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPKGLPLVGYLPFLGPNLHHEFTKVSHRYGPIFKLYLGSKLHIVVNSADLAKVITSEQDESFANRAPHIAGLATSYGGNDIAFADNNANRRNLRKVLVHEVLSNVNLEASHAYRRHEVRKTIKSVHDMIGMEVDINEISFSTVLNVLTNIVWGKGLVEGTKYSNLSEEIRKVVYRIVEIAEGLNISDFFPMLARFDLQGVERKMKKQMKQFDRIFENTISERTNNKNSNHGKQCLQILLELKTKTITTTQLKALVVDIFLGGTDATSAMVEWAMTEILRNKKVMKRVQDELEEIVGLNNIVEESHIPKLKYLDAVFKETFRLHPPLPFLLPRAPSKSCTVGGYTVPKGATIFLNVWAIQRDPRHWENPSEFNPDRFLNNNNGSTEKWDYSGTNLTFLPFGSGRRRCPGIPLGEKMMMHILASLMHSFDWSLPNGEEHDLSDKFGIALKKKKPLVAIPTRRLSDENLYM"),
        ("Design26159", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPYGLPLLGYLPFFLGPSLHHELTKMAHRYGPIFKLYLGSKLHIVVNSADLAKVITSEQDESFANRAPHIAGLATSYGANDIAFADNNANRRNLRKILVHEILSNVNLEASHAYRRREVRKTIKSVHDMIGMPVDINEMSFSTVVNVLTSIVWGNSMVEGTKHSNLGEEIRKVVSEIVDIAEGLNISDFFPKLARFDLQGVEQKMKRKMKQFDWIFETTIEERINLKSTHGEDALKHEGRKDFLQILLELKDKKSITMTQLKALVVDIFLGGTDATSAMVEWAMAEILKNQKVMKKVQDELAEIVGLKNMVEESHLPKLKYLNATFKETFRLHTPLPVLLPRTPSKSCMVGGYLIPRDSTVFLNVWAIQRDPQHWENPSEFNPERFLNYEGSGKWDYSGTNSKYFPFGSGRRRCPGIPLAEKMMLHILASLLHSFDWSLPKGEDHDLFEKFGIALKKKKPLVAVPSPRLIDLSLYM"),
        ("Design58", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPKGLPLVGYLPFLGPNLHQELTKMAHRYGPIFKLYLGSKLHIVVNSADLAKVVTGEQDESFANRAPHIAGLATSYNASDIAFADNNANRRKLRKVLVHEVLSNVNLEASHAYRRREVRKTIKNVHEIIGNEVDINEIAFSTVLSVLTSIVWGKSMVEGAKYSNLVAEMRKFVSGVVEIAGELNISDFFPMLARFDFQGVERRMKKQMKLFDKIFESTVEERINSRKSVEKEDFLQILLELQEQNNETSITMTQMKALVVDIFLGGTDATSAMIEWAMTEILRNRQVMKKVQDELAEIVGLNNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTIPKGSTIFLNVWAIQRDPQYWENPSEFNPERFLNYKGSEKWDYAGTNSKFFPLGSGRRRCPGVSLGEKMMMHILASLLHSFDWSLPTGQKLDLSDKFGIALKKRKPLIAVPSPRLNDASLYM"),
        ("Design4779", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPRGLPLVGYLPFLGPNLHQELTKMAHRYGPIFKLYLGSKLHIVVNSADLAKVVTGEQDESFANRAPHIAGLATSYNASDIAFADNNANRRKLRKVLVHEVLSNVNLEASHAYRRREVRKTIKNVHEIIGNEVDINEIAFSTVLSILTSIVWGKSMVEGAKYTNLVAEMRKFVSGVVEIAGELNISDFFPMLARFDFQGVERRMKKQMKLFDKIFESTVEERINSSKKEGRKDFLQILLELQEQNNETSITMTQMKALVVDIFLGGTDATSAMVEWAMTEILRNRQVMKKVQDELAEIVGLNNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTIPKGSTIFLNVWAIQRDPQYWENPSEFNPERFLNYKGSEKWDYAGTNSKFFPLGSGRRRCPGVSLGEKMMMHILASLLHSFDWSLPTGQKLDLSDKFGIALKKRKPLIAVPSPRLNDASLYM"),
        ("Design3644", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPRGLPLVGYLPFLGPNLHHELTKMAHRYGPIFKLYLGSKLHIVVNSADLAKVVTGEQDESFANRDPHIAGLATSYNANDIAFADNNANRRKLRKVLVHEVLSNVNLEASHAYRRREVRKTIKNVHEIIGNEVDINEIAFSTVLSVLTSIVWGKSMVKGAKYPNLVAEMRKFVSGVVEIAGELNISDFFPMLARFDFQGVERRMKKQMKLFDKIFESTVEERINSRKKIARKDFLQILLELKEQNNETSITMTQMKALVVDIFLGGTDATSAMIEWAMTEILRNRQVMKKVQDELAEIVGLNNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTIPKGSTIFLNVWAIQRDPQYWENPSEFNPERFLNYEGSEKWDYAGTNSKFFPLGSGRRRCPGIPLGEKMMMHILASLMHSFDWSLPEGEKLDLSDKFGIALKKKKPLIAVPSPRLNDASLYM"),
        ("Design2205", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPRGLPLVGYLPFLGPNLHHELDKMAHRYGPIFKLYLGSKLHIVVNSADLAKVVTGEQDESFANRAPHIAGLATSYNASDIAFADNNANRRKLRKVLVHEVLSNVNLEASHAYRRREVRKTIKNVHEIIGNEVDINEIAFSTVLSVLTSIVWGKSMVKGAKYGNLVAEMRKFVSGVVEIAGELNISDFFPMLARFDFQGVERRMKKQMKLFDKIFETTVEERTNSSKKKVKKDFLQVLLELKEQNNETSINMTQMKALVVDIFLGGTDATSAMIEWAMTEILRNKQVMKKVQDELAEVVGLNNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTIPKGSTIFLNVWAIQRDPQYWENPSEFNPERFLNYKGSEKWDYAGTNSKFFPLGSGRRRCPGVSLGEKMMMHILASLLHSFDWSLPEGQKLDLSDKFGIALKKKKPLIAIPSPRLNDASLYM"),
        ("Design4129", "MASNELAFSALLVTLVLVLISWYKREISNSRKAGTPPLPPGPRGLPLVGYLPFLGPNLHQELTKMAHRYGPIFKLYLGSKLHIVVNSADLAKVVTGEQDESFANRAPHIAGLATSYNASDIAFADNNANRRKLRKVLVHEVLSNVNLEASHAYRRREVRKTIKNVHEIIGNEVDINEIAFSTVLSVLTSIVLKGSNIAAEMRKFVSGVVEIAGELNISDFFPMLARFDFQGVERRMKKQMKLFDKIFESTVEERINSRSAIKEEAVKEEGRKDFLQILLELQEQNNETSITMTQMKALVVDIFLGGTDATSAMIEWAMTEILRNRQVMKKVQDELAEIVGLNNIVEESHLPKLKYLDAVFKETFRLHPPLPFLLPRAPNKSCTVGGYTIPKGSTIFLNVWAIQRDPQYWENPSEFNPERFLNYKGSEKWDYAGTNSKFFPLGSGRRRCPGVSLGEKMMMHILASLLHSFDWSLPTGQKLDLSDKFGIALKKRKPLIAVPSPRLNDASLYM")
    ]
    substrate_smiles = "C1=CC(=C(C=C1C=O)O)C2=CC(=O)C=CC2=O"

    # 运行批量预测
    models = init_models()
    results = batch_predict(models, enzyme_list, substrate_smiles)

    # 输出表格
    print("===== 所有酶动力学参数预测结果 =====")
    print(f"{'酶名称':<15} {'kcat值':<8} {'KM值':<8} {'kcat/KM值':<10}")
    print("-" * 50)
    for res in results:
        print(f"{res['酶名称']:<15} {res['kcat值']:<8} {res['KM值']:<8} {res['kcat/KM值']:<10}")